(()=>{
 const section=document.querySelector('.creator-network');if(!section)return;
 const scene=section.querySelector('.network-scene'),stage=section.querySelector('.network-stage'),people=[...section.querySelectorAll('.network-person')],svg=section.querySelector('.network-connections'),panel=section.querySelector('.network-popover'),close=panel.querySelector('.network-close');
 const reduce=matchMedia('(prefers-reduced-motion:reduce)');let paths=[],active=null,pinned=false,closeTimer=0,frame=0,keyboard=false,suppressFocus=false,suppressHover=false;
 section.classList.add('is-network-enhanced');
 function measure(){
  const w=scene.clientWidth,h=scene.clientHeight;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.replaceChildren();
  paths=people.map(person=>{const path=document.createElementNS('http://www.w3.org/2000/svg','path');const x=person.offsetLeft,y=person.offsetTop;path.setAttribute('d',`M ${w/2} ${h*.48} C ${w/2+(x-w/2)*.55} ${h*.48}, ${x} ${h*.48+(y-h*.48)*.5}, ${x} ${y}`);path.setAttribute('pathLength','1');svg.append(path);return path});paint();if(active)position();
 }
 function paint(){frame=0;const distance=Math.max(1,section.offsetHeight-stage.offsetHeight),top=section.getBoundingClientRect().top;const progress=Math.max(0,Math.min(1,innerHeight<=640?(innerHeight*.75-top)/(section.offsetHeight*.75):-top/distance));people.forEach((person,i)=>{const amount=reduce.matches||keyboard?1:Math.max(0,Math.min(1,(progress-i*.045)/.2));const eased=1-Math.pow(1-amount,3);person.style.setProperty('--reveal',eased);person.classList.toggle('is-revealed',amount>.02);paths[i]?.style.setProperty('--reveal',eased);if(active===person&&amount<=.02)hide()});}
 function schedule(){if(!frame)frame=requestAnimationFrame(paint)}
 function position(){if(!active)return;const r=active.getBoundingClientRect(),s=scene.getBoundingClientRect();const width=panel.offsetWidth,height=panel.offsetHeight;let left=r.left-s.left+r.width/2-width/2;left=Math.max(8,Math.min(scene.clientWidth-width-8,left));let top=r.bottom-s.top+14;if(top+height>scene.clientHeight-8)top=r.top-s.top-height-14;panel.style.left=left+'px';panel.style.top=Math.max(8,top)+'px';}
 function show(person,lock=false){clearTimeout(closeTimer);if(pinned&&!lock&&active!==person)return;active=person;if(lock)pinned=true;people.forEach((p,i)=>{const selected=p===person;p.querySelector('button').setAttribute('aria-expanded',String(selected));paths[i]?.classList.toggle('is-active',selected)});panel.querySelector('h3').textContent=person.dataset.name;panel.querySelector('.network-story').textContent=`${person.dataset.name} will make a new account talking about your brand and test two creative angles.`;const tags=panel.querySelector('.network-angles');tags.replaceChildren();person.dataset.angles.split('|').forEach((angle,i)=>{const tag=document.createElement('span');tag.textContent=`Angle ${i+1} · ${angle}`;tags.append(tag)});panel.hidden=false;position();}
 function hide(){clearTimeout(closeTimer);pinned=false;active=null;panel.hidden=true;people.forEach((p,i)=>{p.querySelector('button').setAttribute('aria-expanded','false');paths[i]?.classList.remove('is-active')});}
 function deferHide(){clearTimeout(closeTimer);if(!pinned)closeTimer=setTimeout(()=>{if(!panel.matches(':hover')&&!panel.contains(document.activeElement)&&!active?.contains(document.activeElement))hide()},160)}
 document.addEventListener('pointermove',()=>{suppressHover=false},{capture:true,passive:true});
 people.forEach(person=>{const button=person.querySelector('button');const hover=e=>{if(e.pointerType==='mouse'&&!suppressHover)show(person)};button.addEventListener('pointerenter',hover);button.addEventListener('pointermove',hover);person.addEventListener('pointerleave',deferHide);button.addEventListener('focus',()=>{if(!suppressFocus)show(person)});button.addEventListener('blur',deferHide);button.addEventListener('click',()=>{if(active===person&&pinned){hide();return}show(person,true)});});
 panel.addEventListener('pointerenter',()=>clearTimeout(closeTimer));panel.addEventListener('pointerleave',deferHide);
 function dismiss(){suppressHover=true;const button=active?.querySelector('button');hide();if(button){suppressFocus=true;button.focus({preventScroll:true});suppressFocus=false}}
 close.addEventListener('click',dismiss);section.addEventListener('keydown',e=>{if(e.key==='Escape'){dismiss();e.stopPropagation()}if(e.key==='Tab'){keyboard=true;paint()}});
 document.addEventListener('pointerdown',e=>{if(active&&!panel.contains(e.target)&&!e.target.closest('.network-person'))hide()});
 addEventListener('scroll',()=>{schedule();if(active)position()},{passive:true});new ResizeObserver(measure).observe(scene);reduce.addEventListener('change',measure);document.fonts.ready.then(measure);measure();
})();
