import { readFile, readdir, mkdir, writeFile, cp } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const directory = path.dirname(fileURLToPath(import.meta.url));
const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
function url(value) {
  if (/^https:\/\//.test(value) || /^\/(?!\/)[\w/.-]+$/.test(value)) return escape(value);
  throw new Error(`Unsupported proposal URL: ${value}`);
}
const arrow = '<span class="button-arrow" aria-hidden="true">↗</span>';
const link = (href, title, type = 'button') => `<a class="${type}" href="${href}">${escape(title)}${arrow}</a>`;
const sectionLabel = (number, text) => `<p class="eyebrow"><span>${number}</span>${text}</p>`;

export async function buildProposals(outputDir) {
  await cp(path.join(directory, 'assets'), path.join(outputDir, 'proposal-assets'), { recursive: true });
  const files = (await readdir(directory)).filter(file => file.endsWith('.json')).sort();
  const pages = [];
  for (const file of files) {
    const data = JSON.parse(await readFile(path.join(directory, file), 'utf8'));
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(data.slug) || ['assets', 'proposal-assets', 'index', 'dist'].includes(data.slug)) throw new Error(`Invalid proposal slug in ${file}`);
    const brand = escape(data.brand), booking = url(data.bookingUrl);
    const cta = (text = 'Let’s build your wave', type = 'button') => link(booking, text, type);
    const portraitPositions = [[50,5,72,0,0],[77,14,76,20,0],[94,36,80,40,0],[94,64,72,60,0],[77,86,80,80,0],[50,96,72,100,0],[23,86,80,0,20],[6,64,68,20,20],[6,36,74,40,20],[23,14,80,60,20]];
    const portraits = portraitPositions.map(([x,y,size,cropX,cropY], i) => `<span class="creator" style="--x:${x}%;--y:${y}%;--size:${size}px;--cx:${cropX}%;--cy:${cropY}%;--i:${i}"><span class="creator-face"></span><span class="creator-badge">${String(i+1).padStart(2,'0')}</span></span>`).join('');
    const goals = data.goals.map((goal, i) => `<article class="goal"><span class="number">0${i+1}</span><h3>${escape(goal.title)}</h3><p>${escape(goal.description)}</p></article>`).join('');
    const bank = data.playbook.entries.length ? `<div class="bank-entries">${data.playbook.entries.map((entry, i) => `<a href="${url(entry.url)}" class="bank-entry"><span class="number">${String(i+1).padStart(2,'0')}</span><span><small>${escape(entry.format)}</small><h4>${escape(entry.title)}</h4><p>${escape(entry.description)}</p></span><span aria-hidden="true">↗</span></a>`).join('')}</div>` : `<div class="bank-empty"><span class="empty-index" aria-hidden="true">01—∞</span><div><h4>Good ideas start here.</h4><p>Your curated content references, hooks and formats will live in this space.</p><span class="status-label">Content bank coming next</span></div></div>`;
    const samples = data.creatives.length ? data.creatives.map((creative, i) => `<article class="sample"><div class="sample-media">${creative.video ? `<video controls playsinline preload="none" poster="${url(creative.poster)}" aria-label="${escape(creative.title)}"><source src="${url(creative.video)}" type="video/mp4">${creative.captions ? `<track kind="captions" src="${url(creative.captions)}" srclang="en" label="English" default>` : ''}</video>` : `<a href="${url(creative.url)}" aria-label="View ${escape(creative.title)}"><img src="${url(creative.poster)}" alt="${escape(creative.alt || creative.title)}" loading="lazy" width="540" height="960"></a>`}</div><div class="sample-caption"><span>0${i+1}</span><div><h3>${escape(creative.title)}</h3><p>${escape(creative.description)}</p></div></div></article>`).join('') : [1,2,3].map(i => `<article class="sample"><div class="sample-media sample-empty"><span class="sample-top">${brand} <span>× wave.</span></span><div class="sample-empty-copy"><span class="sample-numeral" aria-hidden="true">0${i}</span><p>Sample creative</p><span class="status-label">Coming next</span></div><span class="sample-bottom">MADE FOR YOUR FEED.</span></div><div class="sample-caption"><span>0${i}</span><div><h3>Reserved for your creative</h3><p>Sample UGC will appear here.</p></div></div></article>`).join('');
    const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${brand} × Wave — Your next growth channel</title><meta name="description" content="A personalized creator campaign, content playbook and sample UGC for ${brand}, by Wave."><meta name="robots" content="noindex, nofollow">
<meta property="og:title" content="${brand} × Wave — Make your next wave."><meta property="og:description" content="Your brand. An army of creators. A new organic growth channel."><meta property="og:type" content="website"><meta property="og:url" content="https://waveugc.in/${data.slug}">
<link rel="canonical" href="https://waveugc.in/${data.slug}"><meta name="theme-color" content="#1b43f5">
<link rel="preload" href="/assets/fonts/manrope-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/proposal-assets/proposal.css"><script src="/proposal-assets/proposal.js" defer></script>
</head><body><a class="skip-link" href="#main">Skip to proposal</a>
<div class="site-frame"><header class="proposal-nav"><a class="wordmark" href="/" aria-label="Wave home">wave<span>.</span></a><span class="nav-divider" aria-hidden="true"></span><span class="nav-client">Made for <strong>${brand}</strong></span><nav aria-label="Proposal navigation"><a href="#campaign">The campaign</a><a href="#content-bank">Content bank</a><a href="#creatives">Sample creatives</a></nav>${cta('Let’s talk', 'button button-small')}</header>
<main id="main"><section class="proposal-hero" aria-labelledby="hero-title"><div class="hero-inner"><div class="hero-copy"><p class="eyebrow"><span class="live-dot" aria-hidden="true"></span>A growth plan for ${brand}</p><h1 id="hero-title">${escape(data.hero.headline)} <br><em>${escape(data.hero.emphasis)}</em></h1><p class="hero-description">${escape(data.hero.description)}</p><div class="hero-actions">${link('#content-bank', 'Your free viral content bank', 'button button-lime')}${cta('Talk through the plan', 'text-link')}</div></div><div class="network-wrap"><div class="creator-scene" role="img" aria-label="Illustration of ten creator accounts around ${brand}"><div class="network-orbit orbit-one"></div><div class="network-orbit orbit-two"></div><div class="brand-hub"><span>Your brand. Everywhere.</span><strong>${brand}</strong><small>THE CREATOR NETWORK</small></div>${portraits}</div><p class="network-caption"><span>One brand. Many voices.</span><small>Illustrative creator profiles</small></p></div></div><div class="hero-bottom"><span>THE WAVE CAMPAIGN / PERSONALIZED FOR ${brand}</span><a href="#campaign">The plan, at a glance <span aria-hidden="true">↓</span></a></div></section>
<section class="campaign section-pad" id="campaign" aria-labelledby="campaign-title"><div class="section-heading">${sectionLabel('01','What we’re building')}<div class="heading-split"><h2 id="campaign-title">${escape(data.campaign.headline)}</h2><div><p>${escape(data.campaign.description)}</p><p>${escape(data.campaign.cadence)}</p></div></div></div><div class="campaign-metrics"><article class="metric metric-green" data-card><span class="metric-label">THE CREATOR ARMY</span><strong>${escape(data.campaign.creators)}</strong><h3>Dedicated creator accounts.</h3><p>New ambassador accounts.<br>Built around ${brand}.</p></article><article class="metric metric-blue" data-card><span class="metric-label">THE CONTENT ENGINE</span><strong>${escape(data.campaign.content)}</strong><h3>Pieces of content.</h3><p>Instagram Reels.<br>YouTube Shorts.</p></article><article class="metric metric-lime" data-card><span class="metric-label">THE DISTRIBUTION</span><strong>${escape(data.campaign.days)}<small>days</small></strong><h3>Of constant presence.</h3><p>Twice a day.<br>From every creator.</p></article></div><div class="section-foot"><span>Your brand. In more feeds. Every day.</span>${cta('Build this for '+data.brand,'text-link')}</div></section>
<section class="goals section-pad" aria-labelledby="goals-title">${sectionLabel('02','What we’re going after')}<h2 id="goals-title">Three things we want <br>to make happen<span class="blue-dot">.</span></h2><div class="goals-grid">${goals}</div></section>
<section class="playbook section-pad" id="content-bank" aria-labelledby="playbook-title"><div class="heading-split"><div>${sectionLabel('03','The thinking behind the content')}<h2 id="playbook-title">${escape(data.playbook.headline)}</h2></div><div class="research-copy"><p>${escape(data.playbook.description)}</p><p class="bold-line">Then we build the viral content playbook.</p></div></div><div class="content-bank"><header class="bank-header"><div><span class="bank-kicker">COMPLIMENTARY / MADE FOR ${brand}</span><h3>Your viral content bank<span>.</span></h3></div><span class="bank-stamp">${brand}<small>× wave.</small></span></header>${bank}<footer class="bank-footer"><span>Built around your audience. Designed to be tested.</span>${data.playbook.url ? link(url(data.playbook.url),'Open the full playbook','text-link') : '<span class="bank-footer-note">Your playbook, all in one place.</span>'}</footer></div></section>
<section class="testing-section section-pad" aria-label="How we test and scale"><div class="testing-grid"><article class="test-panel">${sectionLabel('04','Then we test')}<h2>${escape(data.testing.headline)}</h2><p>${escape(data.testing.description)}</p><ul class="test-variables">${data.testing.variables.map((variable,i)=>`<li><span>0${i+1}</span>${escape(variable)}</li>`).join('')}</ul><p class="test-closing">${escape(data.testing.closing)}</p></article><article class="winner-panel">${sectionLabel('05','Find the winners')}<h2>${escape(data.winners.headline)}</h2><p>${escape(data.winners.description)}</p><div class="winner-statement"><span class="winner-label">THIS IS WHAT WE’RE REALLY BUILDING TOWARDS</span><h3>${escape(data.winners.statement)}</h3></div>${cta('Let’s find your winning ideas','text-link')}</article></div></section>
<section class="creatives section-pad" id="creatives" aria-labelledby="creatives-title"><div class="creative-heading"><div>${sectionLabel('06','From the playbook to the feed')}<h2 id="creatives-title">Made for ${brand}.<br><em>Made to get noticed.</em></h2></div><p>A space for your sample UGC creatives. The thinking, brought to life.</p></div><p class="gallery-hint">Swipe to explore the creatives <span aria-hidden="true">→</span></p><div class="samples-grid" tabindex="0" role="region" aria-label="Sample creative gallery">${samples}</div><div class="section-foot"><span>More than content. A reason to pay attention.</span>${cta('Talk creative with us','text-link')}</div></section>
<section class="result section-pad" aria-labelledby="result-title"><div class="result-grid"><div>${sectionLabel('07','The end result')}<h2 id="result-title">${escape(data.result.headline)}</h2><p class="result-closing">${escape(data.result.closing)}</p></div><ul class="result-list">${data.result.items.map((item,i)=>`<li><span>0${i+1}</span>${escape(item)}</li>`).join('')}</ul></div><div class="final-invite"><div><h3>Let’s build ${brand}’s next wave.</h3><p>A conversation about your brand, your audience and your first ${escape(data.campaign.days)} days.</p></div>${cta('Book a strategy call')}</div></section>
</main><footer class="proposal-footer"><a class="wordmark" href="/" aria-label="Wave home">wave<span>.</span></a><p>Built for ${brand}. By Wave.</p><a href="#main">Back to top <span aria-hidden="true">↑</span></a></footer></div>
<aside class="mobile-dock" aria-label="Quick proposal actions"><a href="#content-bank">Content bank <span aria-hidden="true">↓</span></a><a href="${booking}">Let’s talk <span aria-hidden="true">↗</span></a></aside></body></html>`;
    const destination = path.join(outputDir, data.slug);
    await mkdir(destination, { recursive: true });
    await writeFile(path.join(destination, 'index.html'), html);
    pages.push(`${data.slug}/index.html`);
  }
  return pages;
}
