// Optional strategy module: content stays in each brand's proposal JSON.
export function renderStrategy(strategy, brand, campaign, escape) {
  const list = items => `<ul>${items.map(item => `<li>${escape(item)}</li>`).join('')}</ul>`;
  return `<div class="strategy-playbook">
    <header class="strategy-intro"><span class="strategy-tag">EXAMPLE STRATEGY / ${escape(brand)}</span><p>These angles and ideas draw on proven winning formats. We’ll adapt them for ${escape(brand)}, then keep testing to find what wins for your audience.</p></header>
    <div class="strategy-mix" aria-label="Content mix: 70% proven winners and 30% new angles"><div class="mix-proven"><strong>70<span>%</span></strong><div><h4>Proven winners</h4><p>Familiar winning formats, made specific to your brand.</p></div></div><div class="mix-new"><strong>30<span>%</span></strong><div><h4>New angles</h4><p>Fresh hooks, ideas and executions to find the next winner.</p></div></div></div>
    <p class="mix-caption">Our starting mix across <strong>${escape(campaign.content)} reels</strong>. We’ll learn from performance and scale the creative patterns that consistently outperform.</p>
    <div class="format-principle"><span class="principle-symbol" aria-hidden="true">↗</span><div><h4>One format. Multiple creators. A mini trend.</h4><p>These will be consistent formats where multiple creators upload reels, creating mini trends around ${escape(brand)}. Each creator brings a different voice, hook and execution to the same recognizable idea.</p></div></div>
    <nav class="strategy-jumps" aria-label="Explore strategy audiences"><span>EXPLORE THE ANGLES</span>${strategy.audiences.map((group,i)=>`<a href="#strategy-${escape(group.id)}"><span>0${i+1}</span>${escape(group.label)}<span aria-hidden="true">↘</span></a>`).join('')}</nav>
    ${strategy.audiences.map((group,i)=>`<section class="strategy-audience" id="strategy-${escape(group.id)}" aria-labelledby="strategy-${escape(group.id)}-title"><header class="audience-heading"><span class="audience-index">0${i+1}</span><div><p class="audience-kicker">${group.angles.length} CREATIVE ANGLES / ${group.angles.reduce((count, angle) => count + angle.hooks.length, 0)} EXAMPLE HOOKS</p><h3 id="strategy-${escape(group.id)}-title">${escape(group.label)}</h3><p>${escape(group.intro)}</p></div><a class="audience-back" href="#content-bank">Back to strategy ↑</a></header>
    <details class="audience-insights"><summary>What this audience wants — and what holds them back<span class="details-mark" aria-hidden="true">+</span></summary><table><caption>Audience insights for ${escape(group.label)}</caption><thead><tr><th scope="col">What they want</th><th scope="col">What we need to overcome</th></tr></thead><tbody><tr><td>${list(group.desires)}</td><td>${list(group.objections)}</td></tr></tbody></table></details>
    <div class="angle-grid">${group.angles.map((angle,j)=>`<article class="angle-card"><div class="angle-card-top"><span class="angle-number">${String(j+1).padStart(2,'0')}</span><span>REPEATABLE SERIES</span></div><h4>${escape(angle.title)}</h4>${angle.execution?`<p class="angle-execution">${escape(angle.execution)}</p>`:''}<blockquote>“${escape(angle.hooks[0])}”</blockquote><details class="angle-hooks"><summary>${angle.hooks.length - 1} more example hooks<span class="details-mark" aria-hidden="true">+</span></summary>${angle.hooks.slice(1).map(hook=>`<p>“${escape(hook)}”</p>`).join('')}</details></article>`).join('')}</div></section>`).join('')}
    <footer class="strategy-goal"><span>THE GOAL</span><h3>Find repeatable winning formats.<br><em>Then build the wave around them.</em></h3><p>This is an example strategy. Once we launch, we’ll test hundreds of combinations of angles, hooks, creators and executions, then scale the patterns that work across the creator network.</p><small>Hooks are creative starting points. Product names, prices, comparisons and reactions will be confirmed for the final scripts.</small></footer>
  </div>`;
}
